"""empty message

Revision ID: 6ab02a7e91fc
Revises: None
Create Date: 2018-08-24 21:21:34.489323

"""

# revision identifiers, used by Alembic.
revision = '6ab02a7e91fc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('coordinates_long', sa.Float(), nullable=True),
    sa.Column('coordinates_lat', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('cover_pic_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('drive_folder', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moments_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('signup_date', sa.String(), nullable=True),
    sa.Column('last_login', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moment_user_association',
    sa.Column('moments_id', sa.Integer(), nullable=True),
    sa.Column('moments_users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['moments_id'], ['moments.id'], ),
    sa.ForeignKeyConstraint(['moments_users_id'], ['moments_users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moment_user_association')
    op.drop_table('moments_users')
    op.drop_table('moments')
    # ### end Alembic commands ###
